/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.librarylogin;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.io.*;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
//import static my.librarylogin.LoggedStudent.resize;
//import java.regex.*;

/**
 *
 * @author Intel
 */
public class RegisterNow extends javax.swing.JFrame {

    /**
     * Creates new form RegisterNow
     */
    public static String path;
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterNow().setVisible(true);
            }
        });
    }
    public RegisterNow() {
        initComponents();
        this.setVisible(true);
        this.setLocation(275,100);
        //rn.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner2 = new javax.swing.JSpinner();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        cb2 = new javax.swing.JComboBox<>();
        t3 = new javax.swing.JPasswordField();
        t4 = new javax.swing.JPasswordField();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        b3 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("New Registration");

        l1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        l1.setText("Student ID");

        l2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        l2.setText("Name");

        l3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        l3.setText("Year");

        l4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        l4.setText("Branch");

        l5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        l5.setText("Create Password");

        l6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        l6.setText("Confirm Password");

        t1.setColumns(10);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        t2.setColumns(10);
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Civil", "CSE", "EC", "ECE", "IT", "Mec" }));

        t3.setColumns(10);

        t4.setColumns(10);

        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setText("Submit");
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b1.setText("Cancel");
        b1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Upload Image");

        t5.setColumns(10);

        b3.setText("Upload");
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1)
                            .addComponent(l2)
                            .addComponent(l3)
                            .addComponent(l4)
                            .addComponent(l5)
                            .addComponent(l6)
                            .addComponent(jLabel2))
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t2)
                                .addComponent(t1)
                                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(b1)
                        .addGap(69, 69, 69)
                        .addComponent(b2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l2)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l4)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l5))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l6)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1)
                            .addComponent(b2))
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
            // TODO add your handling code here:
            boolean usernameExists=false;
            int flag=0;
            String sid=t1.getText();
            String name=t2.getText();
            String pass=t3.getText();
            String conpass=t4.getText();
            String year=cb1.getSelectedItem().toString();
            String branch=cb2.getSelectedItem().toString();
            String str="Select";
            //System.out.println(path);
            
            if(sid.equals("")||name.equals("")||pass.equals("")||conpass.equals("") || path.equals(""))
            {
                JOptionPane.showMessageDialog(this,"All fields are mandatory to fill");
                flag=1;
             }
            
            else if(sid.length()!=4)
            {
                JOptionPane.showMessageDialog(this,"Student Id should be of length 4");
                flag=1;
            }
            else if(branch.equals(str))
            {
                JOptionPane.showMessageDialog(this,"Please select branch");
                flag=1;
            }
            if(!pass.equals(conpass))
            {
                JOptionPane.showMessageDialog(this,"Password did not matched");
                flag=1;
            }
            else
            {
                 if((pass.length()<4) || (pass.length()>20))
                 {
                     JOptionPane.showMessageDialog(this,"Password length should be in between 4 to 20");
                     flag=1;
                 }            
            }
            
            try{
            if(flag==0)
            {
            Connection conn;
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Library","root","kapilkapil");
            PreparedStatement pst=conn.prepareStatement("SELECT * FROM studentinformation WHERE sid='"+ sid +"'");
            //pst.setString(1,s);
            ResultSet r1=pst.executeQuery();
            //String usernameCounter;
             if(r1.next()) 
             {    JOptionPane.showMessageDialog(this,"Username already exists. Try another name");
                   usernameExists = true;
             }
             
             String inputImagePath,outputImagePath;
              inputImagePath=path;
              
              outputImagePath="\\C:\\Users\\Intel\\Desktop\\programs\\JDBC\\Login_application\\src\\my\\images\\demo_2.jpg\\";
              try {
                int scaledWidth = 159;
                int scaledHeight = 165;
                resize(inputImagePath, outputImagePath, scaledWidth, scaledHeight);
             } catch (Exception ex) {
                 System.out.println("Error resizing the image.");
                 ex.printStackTrace();
                }
             File imgfile = new File(outputImagePath);
             FileInputStream fin = new FileInputStream(imgfile);
             if(!usernameExists)
             {
                 usernameExists=false;
                  PreparedStatement pst1=conn.prepareStatement("INSERT INTO studentinformation (sid,sname,syear,sbranch,nbi,image)" + "VALUES (?,?,?,?,?, ?)");
                     pst1.setString(1,sid);
                     pst1.setString(2,name);
                     pst1.setString(3,year);
                     pst1.setString(4,branch);
                     pst1.setString(5,"0");
                     pst1.setBinaryStream(6,(InputStream)fin,(int)imgfile.length());
		     pst1.executeUpdate();
                     pst1.close();
                     conn.close();
              }
            }
            }
            catch(SQLException e) {
                JOptionPane.showMessageDialog(this,"Sql Error44");
            }
            catch ( Exception e ) {
                //System.out.println("KKKK");
                JOptionPane.showMessageDialog(this,e.getMessage());
                }
            try{
                if(flag==0)
                {
                 Connection conn1;
                     Class.forName("com.mysql.jdbc.Driver");
                     conn1=DriverManager.getConnection("jdbc:mysql://localhost:3306/Library","root","kapilkapil");
                     PreparedStatement pst2=conn1.prepareStatement("INSERT INTO studentpass (sid,pass)" + "VALUES (?,?)");
                     pst2.setString(1,sid);
                     pst2.setString(2,pass);
                     pst2.executeUpdate();
                     JOptionPane.showMessageDialog(this,"Successfull !!!  Login now");
                     StudentLogin sl=new StudentLogin();
                     sl.setVisible(true);   
                     pst2.close();
                     conn1.close();
                     dispose();
            }
    }
            catch(SQLException e) {
                JOptionPane.showMessageDialog(this,"Sql Error44");
            }
            catch ( Exception e ) {
                //System.out.println("KKKK");
                JOptionPane.showMessageDialog(this,e.getMessage());
                }
            
            
            
            
    }//GEN-LAST:event_b2ActionPerformed
    public static void resize(String inputImagePath,String outputImagePath, int scaledWidth, int scaledHeight)throws IOException {
        System.out.println("RESIZE func");  
        File inputFile = new File(inputImagePath);
        BufferedImage inputImage = ImageIO.read(inputFile);
        BufferedImage outputImage = new BufferedImage(scaledWidth,
        scaledHeight, inputImage.getType());
        Graphics2D g2d = outputImage.createGraphics();
        g2d.drawImage(inputImage, 0, 0, scaledWidth, scaledHeight, null);
        g2d.dispose();
        String formatName = outputImagePath.substring(outputImagePath
            .lastIndexOf(".") + 1);
        ImageIO.write(outputImage, formatName, new File(outputImagePath));
       }
    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        StudentLogin sl=new StudentLogin();
        sl.setVisible(true);
        this.dispose();
        sl.setLocation(250,150);
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
          File selectedFile = fileChooser.getSelectedFile();
          //System.out.println();
          path=selectedFile.getPath();
          //Pattern p= Pattern.compile(*.jpg);
          int n=path.length();
          String s1=path.substring(n-4,n);
          String s2=path.substring(n-5,n);
          if(s1.equals(".jpg") || s1.equals(".png") || s2.equals(".jpeg"))
            t5.setText(path);
          else
              JOptionPane.showMessageDialog(this,"ONLY .png/.jpg/.jpeg files are accepted");
        }
    }//GEN-LAST:event_b3ActionPerformed

    /**
     * @param args the command line arguments
     */
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JPasswordField t3;
    private javax.swing.JPasswordField t4;
    public static javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
